version: '3'

services:
  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./Backend
    container_name: node-api
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/fatih/mongo-backup:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge